export function replaceSpecialChars(str: string): string {
	return (str || "")
		.replaceAll("ä", "&auml;")
		.replaceAll("ö", "&ouml;")
		.replaceAll("ü", "&uuml;")
		.replaceAll("Ä", "&Auml;")
		.replaceAll("Ö", "&Ouml;")
		.replaceAll("Ü", "&Uuml;")
		.replaceAll("ß", "&szlig;")

		// French
		.replaceAll("à", "&agrave;")
		.replaceAll("â", "&acirc;")
		.replaceAll("æ", "&aelig;")
		.replaceAll("ç", "&ccedil;")
		.replaceAll("é", "&eacute;")
		.replaceAll("è", "&egrave;")
		.replaceAll("ê", "&ecirc;")
		.replaceAll("ë", "&euml;")
		.replaceAll("î", "&icirc;")
		.replaceAll("ï", "&iuml;")
		.replaceAll("ô", "&ocirc;")
		.replaceAll("œ", "&oelig;")
		.replaceAll("ù", "&ugrave;")
		.replaceAll("û", "&ucirc;")
		.replaceAll("ÿ", "&yuml;")
		.replaceAll("À", "&Agrave;")
		.replaceAll("Â", "&Acirc;")
		.replaceAll("Æ", "&AElig;")
		.replaceAll("Ç", "&Ccedil;")
		.replaceAll("É", "&Eacute;")
		.replaceAll("È", "&Egrave;")
		.replaceAll("Ê", "&Ecirc;")
		.replaceAll("Ë", "&Euml;")
		.replaceAll("Î", "&Icirc;")
		.replaceAll("Ï", "&Iuml;")
		.replaceAll("Ô", "&Ocirc;")
		.replaceAll("Œ", "&OElig;")
		.replaceAll("Ù", "&Ugrave;")
		.replaceAll("Û", "&Ucirc;")
		.replaceAll("Ÿ", "&Yuml;")

		// Spanish
		.replaceAll("á", "&aacute;")
		.replaceAll("í", "&iacute;")
		.replaceAll("ñ", "&ntilde;")
		.replaceAll("Á", "&Aacute;")
		.replaceAll("Í", "&Iacute;")
		.replaceAll("Ñ", "&Ntilde;")
		.replaceAll("ó", "&oacute;")
		.replaceAll("ú", "&uacute;")

		// Portuguese
		.replaceAll("ã", "&atilde;")
		.replaceAll("õ", "&otilde;")
		.replaceAll("Ã", "&Atilde;")
		.replaceAll("Õ", "&Otilde;")
		.replaceAll("à", "&agrave;")
		.replaceAll("Á", "&Aacute;")
		.replaceAll("ç", "&ccedil;")
		.replaceAll("Ç", "&Ccedil;")
		.replaceAll("â", "&acirc;")
		.replaceAll("ê", "&ecirc;")
		.replaceAll("ô", "&ocirc;")
		.replaceAll("Â", "&Acirc;")
		.replaceAll("Ê", "&Ecirc;")
		.replaceAll("Ô", "&Ocirc;")

		// Polish (use numeric entities for guaranteed coverage)
		.replaceAll("ą", "&#261;")
		.replaceAll("ć", "&#263;")
		.replaceAll("ę", "&#281;")
		.replaceAll("ł", "&#322;")
		.replaceAll("ń", "&#324;")
		.replaceAll("ś", "&#347;")
		.replaceAll("ż", "&#380;")
		.replaceAll("ź", "&#378;")
		.replaceAll("Ą", "&#260;")
		.replaceAll("Ć", "&#262;")
		.replaceAll("Ę", "&#280;")
		.replaceAll("Ł", "&#321;")
		.replaceAll("Ń", "&#323;")
		.replaceAll("Ś", "&#346;")
		.replaceAll("Ż", "&#379;")
		.replaceAll("Ź", "&#377;");
}
